2021-12-05 17:19:53,659 - trainer.py[line:25] - INFO: Running with identifier 20211205_171953
2021-12-05 17:19:53,659 - trainer.py[line:27] - INFO: Saving log to log\rot360\20211205_171953\run.log
2021-12-05 17:19:53,660 - trainer.py[line:28] - INFO: Using args: [('log_name', 'rot360'), ('data_train', 'Shared/Rot360'), ('data_eval', None), ('output_checkpoint_dir', 'checkpoint'), ('eval_per_epoch', 20), ('log_dir', 'log'), ('tf_dir', 'tensorboard'), ('output_dir', 'output'), ('not_ignore_warning', False), ('enable_tensorboard', True), ('pack', True)]
2021-12-05 17:19:53,663 - trainer.py[line:39] - INFO: Using tensorboard, store at: tensorboard\rot360\20211205_171953
2021-12-05 17:19:53,663 - trainer.py[line:40] - INFO: Using training data: Shared/Rot360
2021-12-05 17:19:53,663 - trainer.py[line:42] - INFO: Pack this file using this command if training finished: --log_dir log --log_name rot360 --identifier 20211205_171953 --output_checkpoint_dir checkpoint --data_dir Shared/Rot360
2021-12-05 17:19:53,664 - train.py[line:127] - INFO: Running model resnet50
2021-12-05 17:19:53,664 - train.py[line:67] - WARNING: Dataset not found, searching renamed-dataset......
2021-12-05 17:19:53,665 - train.py[line:74] - WARNING: Load dataset with renaming dataset......
2021-12-05 17:19:53,665 - trainer.py[line:54] - ERROR: [Errno 2] No such file or directory: 'Shared/Rot360\\Shared/Rot360\\data_test_1w_rot360.npy'
