2021-12-05 17:10:21,752 - trainer.py[line:25] - INFO: Running with identifier 20211205_171021
2021-12-05 17:10:21,752 - trainer.py[line:27] - INFO: Saving log to log\rot360\20211205_171021\run.log
2021-12-05 17:10:21,752 - trainer.py[line:28] - INFO: Using args: [('log_name', 'rot360'), ('data_train', 'Shared/Rot360'), ('data_eval', None), ('output_checkpoint_dir', 'checkpoint'), ('eval_per_epoch', 20), ('log_dir', 'log'), ('tf_dir', 'tensorboard'), ('output_dir', 'output'), ('not_ignore_warning', False), ('enable_tensorboard', True), ('pack', True)]
2021-12-05 17:10:21,758 - trainer.py[line:39] - INFO: Using tensorboard, store at: tensorboard\rot360\20211205_171021
2021-12-05 17:10:21,758 - trainer.py[line:40] - INFO: Using training data: Shared/Rot360
2021-12-05 17:10:21,758 - trainer.py[line:42] - INFO: Pack this file using this command if training finished: --log_dir log --log_name rot360 --identifier 20211205_171021 --output_checkpoint_dir checkpoint --data_dir Shared/Rot360
2021-12-05 17:10:21,758 - train.py[line:123] - INFO: Running model resnet50
2021-12-05 17:10:21,760 - trainer.py[line:54] - ERROR: [Errno 2] No such file or directory: 'Shared/Rot360\\data.npy'
