2021-11-30 20:22:09,288 - trainer.py[line:25] - INFO: Running with identifier 20211130_202209
2021-11-30 20:22:09,288 - trainer.py[line:27] - INFO: Saving log to log\mix_test\20211130_202209\run.log
2021-11-30 20:22:09,288 - trainer.py[line:28] - INFO: Using args: [('log_name', 'mix_test'), ('data_train', 'dataset/output'), ('data_eval', 'dataset/cifar_10_standard_test'), ('output_checkpoint_dir', 'checkpoint'), ('eval_per_epoch', 20), ('log_dir', 'log'), ('tf_dir', 'tensorboard'), ('output_dir', 'output'), ('not_ignore_warning', False), ('enable_tensorboard', True)]
2021-11-30 20:22:09,291 - trainer.py[line:39] - INFO: Using tensorboard, store at: tensorboard\mix_test\20211130_202209
2021-11-30 20:22:09,291 - train.py[line:97] - INFO: Running model resnet50
2021-11-30 20:22:09,292 - trainer.py[line:49] - ERROR: [Errno 2] No such file or directory: 'dataset/output\\data.npy'
